Object: Remove error on disconnect of locked signals
According to https://github.com/godotengine/godot/commit/37c4a7be41656daafa990dc3d4d286bea7b01d7a#commitcomment-36651823
and as confirmed by @reduz, this seems not to be necessary now that we
copy-on-write.

This triggered freeze scenarios in cases where a node would be deleted
while being used as a target in a signal emission.

Fixes #34650.
Fixes #34769.

Now those two errors go back to reporting:
```
ERROR: emit_signal: Condition ' !target ' is true. Continuing..:
   At: core/object.cpp:1191.
```