Fix warning using ERR_FAIL_INDEX on unsigned int
This method starting being used in 12e1034306fef668f5e5a82301d49842a3f0d6e4,
which now triggers this warning from GCC 10:
```
./core/error_macros.h:151:25: error: comparison of unsigned expression in '< 0' is always false [-Werror=type-limits]
```